
import React from 'react';
import { 
  Laptop, 
  Shirt, 
  Armchair, 
  Cpu, 
  GraduationCap, 
  HeartPulse, 
  ChefHat, 
  Smartphone, 
  Watch, 
  Store 
} from 'lucide-react';
import { Category, Product, Seller, UserProfile } from './types';

export const CATEGORIES: Category[] = [
  { id: 'electronics', name: 'Electronics', icon: 'Laptop', description: 'High-performance computing and gadgets.' },
  { id: 'fashion', name: 'Fashion', icon: 'Shirt', description: 'Premium apparel and designer wear.' },
  { id: 'furniture', name: 'Furniture', icon: 'Armchair', description: 'Authentic wood and modern home decor.' },
  { id: 'digital', name: 'Digital Products', icon: 'Cpu', description: 'Software, licenses, and creative assets.' },
  { id: 'education', name: 'Education', icon: 'GraduationCap', description: 'Certified courses and learning materials.' },
  { id: 'health', name: 'Health & Wellness', icon: 'HeartPulse', description: 'Verified supplements and care products.' },
  { id: 'kitchen', name: 'Home & Kitchen', icon: 'ChefHat', description: 'Culinary tools and home essentials.' },
  { id: 'smart-devices', name: 'Smart Devices', icon: 'Smartphone', description: 'IoT and connected home automation.' },
  { id: 'accessories', name: 'Accessories', icon: 'Watch', description: 'Premium watches and tech accessories.' },
  { id: 'handmade', name: 'Local & Handmade', icon: 'Store', description: 'Artisan goods from verified local makers.' },
];

const MOCK_SELLERS: Record<string, Seller> = {
  s1: {
    id: 's1',
    name: 'OmniTech Solutions',
    trustScore: 94,
    metrics: {
      deliveryReliability: 96,
      reviewAuthenticity: 92,
      returnSuccessRate: 98,
      productMatchAccuracy: 95,
      disputeResolutionSpeed: 88
    },
    verified: true,
    totalSales: 15400,
    joinedDate: 'Jan 2021',
    location: 'Bangalore, India'
  },
  s2: {
    id: 's2',
    name: 'Artisan Hub',
    trustScore: 88,
    metrics: {
      deliveryReliability: 85,
      reviewAuthenticity: 95,
      returnSuccessRate: 90,
      productMatchAccuracy: 92,
      disputeResolutionSpeed: 75
    },
    verified: true,
    totalSales: 2100,
    joinedDate: 'Mar 2022',
    location: 'Jaipur, India'
  },
  s3: {
    id: 's3',
    name: 'SwiftBox Retail',
    trustScore: 72,
    metrics: {
      deliveryReliability: 65,
      reviewAuthenticity: 70,
      returnSuccessRate: 75,
      productMatchAccuracy: 80,
      disputeResolutionSpeed: 60
    },
    verified: false,
    totalSales: 850,
    joinedDate: 'Oct 2023',
    location: 'Mumbai, India'
  },
  s4: {
    id: 's4',
    name: 'EduCore Systems',
    trustScore: 91,
    metrics: {
      deliveryReliability: 94,
      reviewAuthenticity: 90,
      returnSuccessRate: 95,
      productMatchAccuracy: 93,
      disputeResolutionSpeed: 85
    },
    verified: true,
    totalSales: 5600,
    joinedDate: 'Feb 2020',
    location: 'Hyderabad, India'
  },
  s5: {
    id: 's5',
    name: 'Wellness Direct',
    trustScore: 85,
    metrics: {
      deliveryReliability: 82,
      reviewAuthenticity: 88,
      returnSuccessRate: 92,
      productMatchAccuracy: 89,
      disputeResolutionSpeed: 78
    },
    verified: true,
    totalSales: 3400,
    joinedDate: 'May 2022',
    location: 'Chennai, India'
  },
  s6: {
    id: 's6',
    name: 'Luxury Chronos',
    trustScore: 97,
    metrics: {
      deliveryReliability: 99,
      reviewAuthenticity: 98,
      returnSuccessRate: 100,
      productMatchAccuracy: 98,
      disputeResolutionSpeed: 95
    },
    verified: true,
    totalSales: 800,
    joinedDate: 'Jan 2019',
    location: 'New Delhi, India'
  }
};

export const PRODUCTS: Product[] = [
  // ELECTRONICS
  {
    id: 'p1',
    name: 'Quantum X-Pro Laptop',
    description: 'Next-generation workstation with liquid cooling and neural processing unit.',
    category: 'electronics',
    price: 145000,
    originalPrice: 160000,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day Easy Returns',
    features: ['RTX 5090 Mobile', '64GB RAM', '2TB SSD', 'Mini-LED Display'],
    tags: ['Gaming', 'Workstation', 'Premium']
  },
  {
    id: 'e2',
    name: 'ProSense 4K Monitor',
    description: '32-inch color-accurate display for professionals and creative editors.',
    category: 'electronics',
    price: 32000,
    originalPrice: 38000,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '10-day replacement',
    features: ['4K UHD', 'HDR10', '99% sRGB', 'USB-C PD'],
    tags: ['Display', 'Productivity']
  },
  {
    id: 'e3',
    name: 'SoundFlow ANC Headphones',
    description: 'World-class noise cancellation with 40-hour battery life and spatial audio.',
    category: 'electronics',
    price: 18999,
    originalPrice: 24999,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 2,
    returnPolicy: '7-day replacement',
    features: ['Active Noise Cancelling', 'Hi-Res Audio', 'Multipoint Connection'],
    tags: ['Audio', 'Travel']
  },
  {
    id: 'e4',
    name: 'VisionTab 11 Pro',
    description: 'Ultra-thin tablet with OLED display and active stylus support.',
    category: 'electronics',
    price: 54999,
    originalPrice: 59999,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day return',
    features: ['120Hz OLED', 'Snapdragon 8 Gen 2', '8GB RAM'],
    tags: ['Tablet', 'Android']
  },
  {
    id: 'e5',
    name: 'Mechanix RGB Keyboard',
    description: 'Hot-swappable mechanical keyboard with custom switches and aluminum frame.',
    category: 'electronics',
    price: 6500,
    originalPrice: 8500,
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: '10-day return',
    features: ['Brown Switches', 'PBT Keycaps', 'USB-C Wired'],
    tags: ['Gaming', 'Peripherals']
  },
  {
    id: 'e6',
    name: 'CoreHub 10-in-1 Dock',
    description: 'Ultimate connectivity for your laptop with dual 4K support and SD slot.',
    category: 'electronics',
    price: 4200,
    originalPrice: 5999,
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 2,
    returnPolicy: '15-day return',
    features: ['100W PD', 'HDMI 2.1', 'Ethernet Port'],
    tags: ['Accessory', 'Office']
  },

  // FASHION
  {
    id: 'p5',
    name: 'Merino Wool Cardigan',
    description: 'Ultra-soft 100% Merino wool cardigan for all seasons.',
    category: 'fashion',
    price: 4500,
    originalPrice: 5500,
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '30-day return policy',
    features: ['100% Merino', 'Breathable'],
    tags: ['Luxury', 'Apparel']
  },
  {
    id: 'f2',
    name: 'Italian Leather Boots',
    description: 'Hand-stitched full-grain leather boots with Goodyear welt construction.',
    category: 'fashion',
    price: 8999,
    originalPrice: 12000,
    image: 'https://images.unsplash.com/photo-1520639889313-721475191c0e?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1520639889313-721475191c0e?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 6,
    returnPolicy: '15-day exchange',
    features: ['Vibram Sole', 'Full Grain Leather', 'Water Resistant'],
    tags: ['Footwear', 'Premium']
  },
  {
    id: 'f3',
    name: 'Tailored Slim Fit Suit',
    description: 'Premium wool-blend suit tailored for a modern aesthetic.',
    category: 'fashion',
    price: 15400,
    originalPrice: 19999,
    image: 'https://images.unsplash.com/photo-1594932224826-94b275b438f8?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1594932224826-94b275b438f8?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 7,
    returnPolicy: '7-day return',
    features: ['Super 120s Wool', 'Modern Fit', 'Unfinished Hem'],
    tags: ['Formal', 'Luxury']
  },
  {
    id: 'f4',
    name: 'Organic Cotton T-Shirt Pack',
    description: 'Pack of 3 sustainable t-shirts made from 100% organic cotton.',
    category: 'fashion',
    price: 1899,
    originalPrice: 2499,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '30-day return',
    features: ['Hypoallergenic', 'Fair Trade', 'Preshrunk'],
    tags: ['Basics', 'Eco-friendly']
  },
  {
    id: 'f5',
    name: 'Waterproof Trench Coat',
    description: 'Classic double-breasted trench coat with removable thermal lining.',
    category: 'fashion',
    price: 7500,
    originalPrice: 9500,
    image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: '15-day return',
    features: ['DWR Coating', 'Detachable Hood', 'Adjustable Belt'],
    tags: ['Outerwear', 'Style']
  },
  {
    id: 'f6',
    name: 'Silk Evening Scarf',
    description: '100% mulberry silk scarf featuring hand-rolled edges.',
    category: 'fashion',
    price: 3200,
    originalPrice: 4500,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: 'No return on silk items',
    features: ['Mulberry Silk', 'Natural Dyes', 'Handmade'],
    tags: ['Accessory', 'Gift']
  },

  // FURNITURE
  {
    id: 'p2',
    name: 'Minimalist Oak Desk',
    description: 'Handcrafted solid oak desk with integrated cable management.',
    category: 'furniture',
    price: 34000,
    originalPrice: 42000,
    image: 'https://images.unsplash.com/photo-1530018607912-eff2df114fbe?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1530018607912-eff2df114fbe?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 7,
    returnPolicy: '7-day Replacement only',
    features: ['Solid White Oak', 'Sustainably Sourced', 'FSC Certified'],
    tags: ['Interior', 'Office', 'Handmade']
  },
  {
    id: 'u2',
    name: 'Ergonomic Mesh Chair',
    description: 'Advanced lumbar support with dynamic recline and breathable mesh.',
    category: 'furniture',
    price: 18500,
    originalPrice: 22000,
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: '15-day return',
    features: ['4D Armrests', 'Synchro-tilt', 'Alloy Base'],
    tags: ['Office', 'Ergonomics']
  },
  {
    id: 'u3',
    name: 'Velvet Accent Sofa',
    description: 'Mid-century modern design with plush velvet upholstery and gold legs.',
    category: 'furniture',
    price: 45000,
    originalPrice: 55000,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 14,
    returnPolicy: 'Furniture: Replacement only',
    features: ['Performance Velvet', 'Solid Pine Frame', 'High-Density Foam'],
    tags: ['Living Room', 'Decor']
  },
  {
    id: 'u4',
    name: 'Marble Top Coffee Table',
    description: 'Italian Carrara marble top with a minimalist black steel base.',
    category: 'furniture',
    price: 12900,
    originalPrice: 15999,
    image: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 8,
    returnPolicy: '7-day replacement',
    features: ['Genuine Marble', 'Scratch Resistant Coat', 'Weighted Base'],
    tags: ['Living Room', 'Artisan']
  },
  {
    id: 'u5',
    name: 'Scandi Floating Bookshelf',
    description: 'Natural pine bookshelf that adds a light, airy feel to any wall.',
    category: 'furniture',
    price: 4500,
    originalPrice: 6000,
    image: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1594620302200-9a762244a156?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '15-day return',
    features: ['Hidden Brackets', 'Solid Wood', 'Eco Finish'],
    tags: ['Storage', 'Modern']
  },
  {
    id: 'u6',
    name: 'LED Smart Floor Lamp',
    description: 'App-controlled floor lamp with 16 million colors and music sync.',
    category: 'furniture',
    price: 3800,
    originalPrice: 5500,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '10-day replacement',
    features: ['WiFi App Control', 'Voice Compatible', 'Dimmable'],
    tags: ['Lighting', 'Smart Home']
  },

  // DIGITAL
  {
    id: 'p3',
    name: 'CloudSync Enterprise License',
    description: 'Lifetime access to enterprise-grade cloud storage and collaboration tools.',
    category: 'digital',
    price: 12500,
    originalPrice: 15000,
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Non-refundable digital asset',
    features: ['5TB Storage', 'Unlimited Users', '24/7 Support'],
    tags: ['SaaS', 'Business', 'Cloud']
  },
  {
    id: 'd2',
    name: 'PhotoMaster Pro Suite',
    description: 'All-in-one photo editing and asset management software for professionals.',
    category: 'digital',
    price: 8400,
    originalPrice: 12000,
    image: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Download guarantee',
    features: ['AI Retouching', 'Batch Processing', 'RAW support'],
    tags: ['Creative', 'Software']
  },
  {
    id: 'd3',
    name: 'SecureVPN 2-Year Plan',
    description: 'Private, high-speed internet access with servers in 94 countries.',
    category: 'digital',
    price: 3500,
    originalPrice: 7000,
    image: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: '30-day money back',
    features: ['No-logs Policy', 'Kill Switch', 'Unlimited Devices'],
    tags: ['Security', 'Privacy']
  },
  {
    id: 'd4',
    name: 'Stock Video 4K Bundle',
    description: 'Collection of 500+ cinematic 4K stock video clips for creators.',
    category: 'digital',
    price: 4999,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Digital only',
    features: ['4K Resolution', 'Royalty Free', 'Commercial License'],
    tags: ['Video', 'Content']
  },
  {
    id: 'd5',
    name: 'CodeCraft IDE Extension Pack',
    description: 'Productivity boosters for VS Code with custom snippets and AI autocomplete.',
    category: 'digital',
    price: 1200,
    originalPrice: 2500,
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Instant Activation',
    features: ['Auto-refactor', 'Custom Themes', 'Cloud Sync'],
    tags: ['DevTools', 'Coding']
  },
  {
    id: 'd6',
    name: 'Vector Asset Library v3',
    description: 'Huge library of editable vector illustrations for web and mobile.',
    category: 'digital',
    price: 2800,
    originalPrice: 5000,
    image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Verify before buy',
    features: ['SVG/EPS format', 'UI Components', 'Free Updates'],
    tags: ['Design', 'Graphics']
  },

  // EDUCATION
  {
    id: 'ed1',
    name: 'Data Science Mastery Course',
    description: 'Comprehensive 6-month path from Python basics to Advanced Machine Learning.',
    category: 'education',
    price: 15999,
    originalPrice: 25000,
    image: 'https://images.unsplash.com/photo-1551288049-bbbda536339a?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1551288049-bbbda536339a?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: '7-day full refund',
    features: ['Live Sessions', 'Industry Projects', 'Job Support'],
    tags: ['Career', 'Data']
  },
  {
    id: 'ed2',
    name: 'Digital Marketing Certificate',
    description: 'Learn SEO, SEM, and Content Strategy from top industry experts.',
    category: 'education',
    price: 8500,
    originalPrice: 12000,
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Partial refund',
    features: ['Hands-on Labs', 'Ad Credits', 'Certification'],
    tags: ['Marketing', 'Business']
  },
  {
    id: 'ed3',
    name: 'SAT Prep Interactive Module',
    description: 'Personalized learning paths for SAT with 50+ mock exams.',
    category: 'education',
    price: 6500,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Satisfaction guaranteed',
    features: ['Adaptive AI', 'Video Solutions', 'Score Tracker'],
    tags: ['TestPrep', 'Academic']
  },
  {
    id: 'ed4',
    name: 'Financial Literacy Workshop',
    description: 'Learn personal tax, investment, and retirement planning (India focused).',
    category: 'education',
    price: 2200,
    originalPrice: 4500,
    image: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1579621970795-87facc2f976d?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Workshop: No refund',
    features: ['Excel Templates', 'Resource Guide', 'Expert Q&A'],
    tags: ['Finance', 'LifeSkills']
  },
  {
    id: 'ed5',
    name: 'Piano Basics Video Series',
    description: 'Master the piano with our step-by-step visual method.',
    category: 'education',
    price: 3400,
    originalPrice: 6000,
    image: 'https://images.unsplash.com/photo-1520529681614-704046c24816?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1520529681614-704046c24816?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s4,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Verified download',
    features: ['HD Videos', 'Sheet Music', 'App Access'],
    tags: ['Hobby', 'Music']
  },
  {
    id: 'ed6',
    name: 'High School Physics PDF Guide',
    description: 'Concise, high-quality revision notes for Class 11 & 12 Physics.',
    category: 'education',
    price: 499,
    originalPrice: 999,
    image: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Digital',
    estimatedDeliveryDays: 0,
    returnPolicy: 'Digital Copy: No return',
    features: ['Print Ready', 'Formula Sheets', 'Past Papers'],
    tags: ['School', 'StudyNotes']
  },

  // HEALTH & WELLNESS
  {
    id: 'h1',
    name: 'Premium Whey Isolate (2kg)',
    description: 'High-purity protein powder with zero additives and third-party testing.',
    category: 'health',
    price: 6800,
    originalPrice: 8500,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s5,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: 'Replacement only if seal broken',
    features: ['25g Protein/scoop', 'No Sugar', 'Lab Tested'],
    tags: ['Fitness', 'Nutrition']
  },
  {
    id: 'h2',
    name: 'Smart Yoga Mat',
    description: 'Non-slip eco-friendly mat with integrated alignment lines.',
    category: 'health',
    price: 3200,
    originalPrice: 4500,
    image: 'https://images.unsplash.com/photo-1592419044706-39796d40f98c?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1592419044706-39796d40f98c?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s5,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '15-day return',
    features: ['TPE Material', '6mm Cushioning', 'Carry Strap'],
    tags: ['Yoga', 'Mindfulness']
  },
  {
    id: 'h3',
    name: 'Multivitamin Pack (90 Days)',
    description: 'Daily essential nutrients with high bioavailability and vegan shell.',
    category: 'health',
    price: 1499,
    originalPrice: 1999,
    image: 'https://images.unsplash.com/photo-1471864190281-ad5f9f33d4a6?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1471864190281-ad5f9f33d4a6?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s5,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 2,
    returnPolicy: 'Standard return',
    features: ['Vitamin D3 + K2', 'Immune Support', 'Organic Sources'],
    tags: ['Supplements', 'Daily']
  },
  {
    id: 'h4',
    name: 'Deep Tissue Massage Gun',
    description: 'Professional grade percussive therapy with 6 interchangeable heads.',
    category: 'health',
    price: 5999,
    originalPrice: 9999,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '1-year warranty',
    features: ['Quiet Motor', '5 Speeds', 'Case Included'],
    tags: ['Recovery', 'Tech']
  },
  {
    id: 'h5',
    name: 'Blue Light Blocking Glasses',
    description: 'High-quality lenses to reduce eye strain from screen usage.',
    category: 'health',
    price: 1200,
    originalPrice: 2500,
    image: 'https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s5,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '15-day return',
    features: ['Anti-reflective', 'UV Protection', 'Light Frame'],
    tags: ['Eyewear', 'TechLife']
  },
  {
    id: 'h6',
    name: 'Aromatherapy Oil Set',
    description: '100% pure essential oils set including Lavender, Peppermint, and Eucalyptus.',
    category: 'health',
    price: 2400,
    originalPrice: 3500,
    image: 'https://images.unsplash.com/photo-1540348563548-6485e99aa65a?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1540348563548-6485e99aa65a?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: 'Replacement only',
    features: ['Pure Extracts', 'Gift Box', 'Dropper Bottle'],
    tags: ['Wellness', 'Relaxation']
  },

  // KITCHEN
  {
    id: 'k1',
    name: 'ChefPro Digital Air Fryer',
    description: 'Healthier cooking with 360-degree air circulation and touch controls.',
    category: 'kitchen',
    price: 8499,
    originalPrice: 12000,
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '10-day replacement',
    features: ['5.5L Capacity', 'Non-stick basket', '8 Presets'],
    tags: ['Cooking', 'Appliances']
  },
  {
    id: 'k2',
    name: '12-Piece Ceramic Cookware Set',
    description: 'Non-toxic, PFOA-free ceramic non-stick set for safe daily cooking.',
    category: 'kitchen',
    price: 14500,
    originalPrice: 18000,
    image: 'https://images.unsplash.com/photo-1584990344321-2766350c2399?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1584990344321-2766350c2399?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 6,
    returnPolicy: '7-day replacement',
    features: ['Induction Safe', 'Heat Resistant Handles', 'Lid Included'],
    tags: ['Kitchenware', 'Quality']
  },
  {
    id: 'k3',
    name: 'Precision Coffee Grinder',
    description: 'Burr grinder with 40 settings for the perfect espresso or pour-over.',
    category: 'kitchen',
    price: 7200,
    originalPrice: 9500,
    image: 'https://images.unsplash.com/photo-1559056191-4917a3bc70e4?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1559056191-4917a3bc70e4?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day return',
    features: ['Conical Burrs', 'Uniform Grind', 'Compact Design'],
    tags: ['Coffee', 'Morning']
  },
  {
    id: 'k4',
    name: 'Automatic Espresso Machine',
    description: 'Bean-to-cup machine with integrated milk frother and touch screen.',
    category: 'kitchen',
    price: 45000,
    originalPrice: 52000,
    image: 'https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1510972527921-ce03766a1cf1?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: 'Furniture: Replacement only',
    features: ['15 Bar Pressure', 'Self-cleaning', 'Custom Strength'],
    tags: ['Luxury', 'Appliance']
  },
  {
    id: 'k5',
    name: 'Cast Iron Dutch Oven',
    description: 'Enameled 5-quart Dutch oven for slow cooking and perfect bread.',
    category: 'kitchen',
    price: 6800,
    originalPrice: 8900,
    image: 'https://images.unsplash.com/photo-1591123716062-5bb1f5fe972e?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1591123716062-5bb1f5fe972e?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 7,
    returnPolicy: 'Lifetime Warranty',
    features: ['Even Heating', 'Oven Safe 500F', 'Vibrant Color'],
    tags: ['Artisan', 'Cooking']
  },
  {
    id: 'k6',
    name: 'Magnetic Knife Block',
    description: 'Solid walnut block with powerful magnets for safe storage.',
    category: 'kitchen',
    price: 3200,
    originalPrice: 4500,
    image: 'https://images.unsplash.com/photo-1616733224097-404889c0ba0a?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1616733224097-404889c0ba0a?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '15-day return',
    features: ['Genuine Walnut', 'Space Saving', 'Weighted Base'],
    tags: ['Storage', 'Design']
  },

  // SMART DEVICES
  {
    id: 'p4',
    name: 'Vanguard Smart Watch S5',
    description: 'Titanium chassis with blood oxygen monitoring and 14-day battery.',
    category: 'smart-devices',
    price: 24999,
    originalPrice: 29999,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 2,
    returnPolicy: '10-day replacement',
    features: ['Titanium', 'OLED', 'GPS'],
    tags: ['Fitness', 'Wearable']
  },
  {
    id: 's2',
    name: 'Smart Lock Pro (Biometric)',
    description: 'Replace your deadbolt with a secure, fingerprint-access lock.',
    category: 'smart-devices',
    price: 12500,
    originalPrice: 15999,
    image: 'https://images.unsplash.com/photo-1558002038-10330058e040?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1558002038-10330058e040?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day return',
    features: ['Fingerprint ID', 'Auto Unlock', 'Guest Access'],
    tags: ['Security', 'IOT']
  },
  {
    id: 's3',
    name: 'Mesh Wi-Fi 6 System',
    description: 'Whole-home coverage with ultra-fast Wi-Fi 6 speeds for 100+ devices.',
    category: 'smart-devices',
    price: 18000,
    originalPrice: 24000,
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day return',
    features: ['Covers 5000 sq ft', 'Gigabit speed', 'Parental Controls'],
    tags: ['Networking', 'Home']
  },
  {
    id: 's4',
    name: '2K Indoor Security Camera',
    description: 'AI-powered human detection with 360-degree pan and tilt.',
    category: 'smart-devices',
    price: 3800,
    originalPrice: 5500,
    image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 2,
    returnPolicy: '10-day replacement',
    features: ['Night Vision', 'Two-way Audio', 'Cloud Storage'],
    tags: ['Safety', 'Monitor']
  },
  {
    id: 's5',
    name: 'Smart LED Bulb Pack (4)',
    description: 'Energy-efficient RGB bulbs compatible with Alexa and Google Home.',
    category: 'smart-devices',
    price: 2400,
    originalPrice: 3500,
    image: 'https://images.unsplash.com/photo-1550524513-317059df8c52?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1550524513-317059df8c52?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day return',
    features: ['Music Sync', 'Schedules', 'No Hub Needed'],
    tags: ['Lighting', 'Budget']
  },
  {
    id: 's6',
    name: 'Smart Air Purifier v4',
    description: 'HEPA filter removes 99.97% of dust and allergens with real-time air monitoring.',
    category: 'smart-devices',
    price: 15400,
    originalPrice: 19999,
    image: 'https://images.unsplash.com/photo-1585771724684-2827df00632d?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1585771724684-2827df00632d?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s1,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: '10-day replacement',
    features: ['H13 HEPA', 'Low Noise', 'APP Control'],
    tags: ['Health', 'CleanAir']
  },

  // ACCESSORIES
  {
    id: 'a1',
    name: 'Heritage Automatic Watch',
    description: 'Stunning skeleton dial with 80-hour power reserve and sapphire crystal.',
    category: 'accessories',
    price: 45000,
    originalPrice: 58000,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s6,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: 'Insurance Included',
    features: ['Swiss Movement', 'Waterproof 50m', 'Leather Strap'],
    tags: ['Luxury', 'Horology']
  },
  {
    id: 'a2',
    name: 'Carbon Fiber Slim Wallet',
    description: 'Minimalist RFID-blocking wallet that fits 12 cards and cash.',
    category: 'accessories',
    price: 2800,
    originalPrice: 4500,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day return',
    features: ['Aircraft Grade Aluminum', 'RFID Block', 'Lifetime Guarantee'],
    tags: ['EDC', 'Minimalist']
  },
  {
    id: 'a3',
    name: 'Aviation Polarized Sunglasses',
    description: 'Classic aviator frame with high-definition polarized lenses.',
    category: 'accessories',
    price: 6400,
    originalPrice: 8500,
    image: 'https://images.unsplash.com/photo-1511499767390-91f19760a032?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1511499767390-91f19760a032?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 4,
    returnPolicy: 'Standard return',
    features: ['100% UV400', 'Lightweight Alloy', 'Cleaning Kit'],
    tags: ['Fashion', 'Outdoor']
  },
  {
    id: 'a4',
    name: 'Leather Tech Folio',
    description: 'Organize your iPad, cables, and pens in this elegant leather pouch.',
    category: 'accessories',
    price: 4200,
    originalPrice: 6000,
    image: 'https://images.unsplash.com/photo-1511406361295-0a5ff814c0ad?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1511406361295-0a5ff814c0ad?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: 'Artisan return policy',
    features: ['Top Grain Leather', 'YKK Zippers', 'Suede Lining'],
    tags: ['Business', 'Tech']
  },
  {
    id: 'a5',
    name: 'Sterling Silver Cufflinks',
    description: 'Hand-polished 925 silver cufflinks for the discerning professional.',
    category: 'accessories',
    price: 5500,
    originalPrice: 7500,
    image: 'https://images.unsplash.com/photo-1620619767323-b95a89183081?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1620619767323-b95a89183081?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s6,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 6,
    returnPolicy: 'Insured shipping',
    features: ['Hallmarked 925', 'Classic Toggle', 'Gift Box'],
    tags: ['Formal', 'Jewelry']
  },
  {
    id: 'a6',
    name: 'Tactical EDC Pen',
    description: 'Machined aluminum pen with glass breaker and pressurized ink.',
    category: 'accessories',
    price: 1800,
    originalPrice: 2500,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s3,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 3,
    returnPolicy: '15-day return',
    features: ['Emergency Tip', 'Waterproof Ink', 'Clip Mount'],
    tags: ['EDC', 'Tools']
  },

  // LOCAL & HANDMADE
  {
    id: 'm1',
    name: 'Hand-Knotted Wool Rug',
    description: 'Authentic 4x6 wool rug featuring traditional patterns from Rajasthan.',
    category: 'handmade',
    price: 28000,
    originalPrice: 35000,
    image: 'https://images.unsplash.com/photo-1531835597900-51cc0224c797?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1531835597900-51cc0224c797?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 10,
    returnPolicy: 'Final sale - Custom item',
    features: ['100% Wool', 'Artisan Made', 'Eco Dyes'],
    tags: ['Home', 'Authentic']
  },
  {
    id: 'm2',
    name: 'TerraCotta Tea Set',
    description: 'Hand-painted clay tea set for 4, made using age-old techniques.',
    category: 'handmade',
    price: 3200,
    originalPrice: 4500,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 7,
    returnPolicy: 'Replacement on damage',
    features: ['Food Safe', 'Microwave Safe', 'Natural Clay'],
    tags: ['Kitchen', 'Decor']
  },
  {
    id: 'm3',
    name: 'Recycled Wood Wall Art',
    description: 'Modern geometric mosaic created from reclaimed shipping pallets.',
    category: 'handmade',
    price: 5800,
    originalPrice: 8500,
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 9,
    returnPolicy: 'Standard return',
    features: ['Solid Wood', 'Signed by Artist', 'Hanging kit'],
    tags: ['Art', 'Sustainable']
  },
  {
    id: 'm4',
    name: 'Organic Scented Soy Candles',
    description: 'Set of 3 essential oil candles in reusable concrete jars.',
    category: 'handmade',
    price: 1800,
    originalPrice: 2500,
    image: 'https://images.unsplash.com/photo-1570733117311-d990c537a4e1?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1570733117311-d990c537a4e1?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 5,
    returnPolicy: '15-day return',
    features: ['Soy Wax', 'Cotton Wick', '30hr Burn Time'],
    tags: ['Gift', 'Home']
  },
  {
    id: 'm5',
    name: 'Hand-woven Bamboo Basket',
    description: 'Large decorative storage basket woven by local communities.',
    category: 'handmade',
    price: 2400,
    originalPrice: 3200,
    image: 'https://images.unsplash.com/photo-1502444330042-d1a1ddf9bb5c?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1502444330042-d1a1ddf9bb5c?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 6,
    returnPolicy: '15-day return',
    features: ['Natural Fiber', 'Sustainable', 'Lined Interior'],
    tags: ['Storage', 'Artisan']
  },
  {
    id: 'm6',
    name: 'Natural Indigo Scarf',
    description: 'Soft cotton scarf dyed with organic indigo using block print techniques.',
    category: 'handmade',
    price: 3500,
    originalPrice: 4800,
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=800',
    images: ['https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&q=80&w=800'],
    seller: MOCK_SELLERS.s2,
    deliveryType: 'Physical',
    estimatedDeliveryDays: 8,
    returnPolicy: 'Replacement only',
    features: ['100% Cotton', 'Plant Dyes', 'Skin Friendly'],
    tags: ['Fashion', 'Handmade']
  }
];

export const MOCK_USER: UserProfile = {
  id: 'u101',
  name: 'Sai Chethana',
  email: 'sai.chethana@trustloop.com',
  avatar: 'https://i.pravatar.cc/150?u=saichethana',
  joinedDate: 'March 2023',
  accountType: 'Buyer',
  trustScore: 98,
  savedProductIds: ['p1', 'f3', 'm1'],
  orders: [
    {
      id: 'TL-8829-10',
      productId: 'p1',
      productName: 'Quantum X-Pro Laptop',
      productImage: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800',
      status: 'Shipped',
      date: 'May 12, 2024',
      estimatedDelivery: 'May 15, 2024',
      price: 145099,
      sellerName: 'OmniTech Solutions'
    },
    {
      id: 'TL-7721-04',
      productId: 'h3',
      productName: 'Multivitamin Pack (90 Days)',
      productImage: 'https://images.unsplash.com/photo-1471864190281-ad5f9f33d4a6?auto=format&fit=crop&q=80&w=800',
      status: 'Delivered',
      date: 'April 20, 2024',
      estimatedDelivery: 'April 22, 2024',
      price: 1499,
      sellerName: 'Wellness Direct'
    },
    {
      id: 'TL-6610-12',
      productId: 'f4',
      productName: 'Organic Cotton T-Shirt Pack',
      productImage: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800',
      status: 'Delivered',
      date: 'March 05, 2024',
      estimatedDelivery: 'March 08, 2024',
      price: 1899,
      sellerName: 'SwiftBox Retail'
    }
  ],
  reviews: [
    {
      id: 'r1',
      userId: 'u101',
      userName: 'Sai Chethana',
      productName: 'Multivitamin Pack (90 Days)',
      productImage: 'https://images.unsplash.com/photo-1471864190281-ad5f9f33d4a6?auto=format&fit=crop&q=80&w=800',
      rating: 5,
      comment: 'Excellent quality! I feel much more energetic. The packaging was eco-friendly too.',
      date: 'April 25, 2024',
      isVerified: true
    }
  ]
};

export const getIcon = (name: string) => {
  switch (name) {
    case 'Laptop': return <Laptop size={20} />;
    case 'Shirt': return <Shirt size={20} />;
    case 'Armchair': return <Armchair size={20} />;
    case 'Cpu': return <Cpu size={20} />;
    case 'GraduationCap': return <GraduationCap size={20} />;
    case 'HeartPulse': return <HeartPulse size={20} />;
    case 'ChefHat': return <ChefHat size={20} />;
    case 'Smartphone': return <Smartphone size={20} />;
    case 'Watch': return <Watch size={20} />;
    case 'Store': return <Store size={20} />;
    default: return <Store size={20} />;
  }
};
